recentActivepane: 7zpF
projects:
  - id: Crqr
    name: blender-bots
    path: /home/tree/project/blender-bots
    description: 3d viewport에서 사용자의 마우스 위치를 따라서 자율적으로 움직이는 cube를 생성하는 blender plugin
    created_at: "1772408071"
    updated_at: "1772888103"
    selected: false
    project_type: code
  - id: g1SH
    name: tree
    path: /home/tree
    description: todo manager app
    created_at: "1772265581"
    updated_at: "1772888103"
    selected: false
    project_type: code
  - id: 501S
    name: temp
    path: /home/tree/temp
    description: zustand 상태관리 예제 앱
    created_at: "1772265929"
    updated_at: "1772888105"
    selected: false
    project_type: code
  - id: rCmQ
    name: home
    path: /home/tree/home
    description: loaded project
    created_at: "1772888117"
    updated_at: "1772888119"
    selected: false
    project_type: code
  - id: 7zpF
    name: pw-1772889995107
    path: /tmp/tmp_project
    description: playwright e2e project
    created_at: "1772888365"
    updated_at: "1772889997"
    selected: true
    project_type: code
  - id: ue6A
    name: api/app
    path: /home/tree/home/apps/api
    description: monorepo app package
    created_at: "1772888760"
    updated_at: "1772888984"
    selected: false
    project_type: mono
  - id: T4Yu
    name: mobile/app
    path: /home/tree/home/apps/mobile
    description: monorepo app package
    created_at: "1772888760"
    updated_at: "1772888984"
    selected: false
    project_type: mono
  - id: 3ert
    name: script/app
    path: /home/tree/home/apps/script
    description: monorepo app package
    created_at: "1772888760"
    updated_at: "1772888984"
    selected: false
    project_type: mono
  - id: gMsN
    name: app/web
    path: /home/tree/home/apps/web
    description: monorepo app package
    created_at: "1772888760"
    updated_at: "1772888760"
    selected: false
    project_type: mono
  - id: Eypy
    name: article
    path: /home/tree/home/packages/features/article
    description: monorepo feature package
    created_at: "1772888760"
    updated_at: "1772888984"
    selected: false
    project_type: mono
  - id: xxaS
    name: auth
    path: /home/tree/home/packages/features/auth
    description: monorepo feature package
    created_at: "1772888760"
    updated_at: "1772888984"
    selected: false
    project_type: mono
  - id: VcBt
    name: comment
    path: /home/tree/home/packages/features/comment
    description: monorepo feature package
    created_at: "1772888760"
    updated_at: "1772888984"
    selected: false
    project_type: mono
  - id: uvVR
    name: dashboard
    path: /home/tree/home/packages/features/dashboard
    description: monorepo feature package
    created_at: "1772888760"
    updated_at: "1772888984"
    selected: false
    project_type: mono
  - id: jLkN
    name: editor
    path: /home/tree/home/packages/features/editor
    description: monorepo feature package
    created_at: "1772888760"
    updated_at: "1772888984"
    selected: false
    project_type: mono
  - id: Yp7p
    name: reader
    path: /home/tree/home/packages/features/reader
    description: monorepo feature package
    created_at: "1772888760"
    updated_at: "1772888984"
    selected: false
    project_type: mono
  - id: YLSv
    name: user
    path: /home/tree/home/packages/features/user
    description: monorepo feature package
    created_at: "1772888760"
    updated_at: "1772888984"
    selected: false
    project_type: mono
  - id: NHVc
    name: template/desktop
    path: /home/tree/home/template/desktop
    description: monorepo template package
    created_at: "1772888760"
    updated_at: "1772888760"
    selected: false
    project_type: mono
  - id: wpVJ
    name: template/mobile
    path: /home/tree/home/template/mobile
    description: monorepo template package
    created_at: "1772888760"
    updated_at: "1772888760"
    selected: false
    project_type: mono
  - id: 2qZZ
    name: template/web
    path: /home/tree/home/template/web
    description: monorepo template package
    created_at: "1772888760"
    updated_at: "1772888760"
    selected: false
    project_type: mono
  - id: vtez
    name: web/app
    path: /home/tree/home/apps/web/app
    description: monorepo app package
    created_at: "1772888984"
    updated_at: "1772888984"
    selected: false
    project_type: mono
  - id: DhKk
    name: web/public
    path: /home/tree/home/apps/web/public
    description: monorepo app package
    created_at: "1772888984"
    updated_at: "1772888984"
    selected: false
    project_type: mono
  - id: sTed
    name: desktop/astro
    path: /home/tree/home/template/desktop/astro
    description: monorepo template package
    created_at: "1772888984"
    updated_at: "1772888984"
    selected: false
    project_type: mono
  - id: HinQ
    name: mobile/expo
    path: /home/tree/home/template/mobile/expo
    description: monorepo template package
    created_at: "1772888984"
    updated_at: "1772888984"
    selected: false
    project_type: mono
  - id: dS7C
    name: web/astro
    path: /home/tree/home/template/web/astro
    description: monorepo template package
    created_at: "1772888984"
    updated_at: "1772888984"
    selected: false
    project_type: mono
  - id: ArCm
    name: web/blog
    path: /home/tree/home/template/web/blog
    description: monorepo template package
    created_at: "1772888984"
    updated_at: "1772888984"
    selected: false
    project_type: mono
  - id: YEnP
    name: web/blog-feature-gapfix
    path: /home/tree/home/template/web/blog-feature-gapfix
    description: monorepo template package
    created_at: "1772888984"
    updated_at: "1772888984"
    selected: false
    project_type: mono
  - id: CbgR
    name: web/next
    path: /home/tree/home/template/web/next
    description: monorepo template package
    created_at: "1772888984"
    updated_at: "1772888984"
    selected: false
    project_type: mono
