recentActivepane: 501S
projects:
- id: Crqr
  name: blender-bots
  path: /home/tree/project/blender-bots
  description: 3d viewport에서 사용자의 마우스 위치를 따라서 자율적으로 움직이는 cube를 생성하는 blender plugin
  created_at: '1772408071'
  updated_at: '1772408071'
  selected: false
- id: g1SH
  name: tree
  path: /home/tree
  description: todo manager app
  created_at: '1772265581'
  updated_at: '1772265581'
  selected: false
- id: 501S
  name: temp
  path: /home/tree/temp
  description: zustand 상태관리 예제 앱
  created_at: '1772265929'
  updated_at: '1772628287'
  selected: true
- id: LCts
  name: temp2
  path: /home/tree/temp2
  description: calculator app
  created_at: '1772286223'
  updated_at: '1772288543'
  selected: false
- id: lSBU
  name: sampleweb
  path: /tmp/orc-create-ZklC0U
  description: heolloworld를 출력하는 간단한 web app으로
  created_at: '1772610528'
  updated_at: '1772610528'
  selected: false
- id: yFAJ
  name: rust-orc
  path: /tmp/orc-create-default-5LhfM3
  description: heolloworld를 출력하는 간단한 web app으로
  created_at: '1772610683'
  updated_at: '1772610683'
  selected: false
